---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: kavita_latest
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
  - name: kavita_nightly
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
  - name: kavita_canary
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      kavita_latest:
        ansible_user: podman
        kavita_version: latest
      kavita_nightly:
        ansible_user: podman
        kavita_version: nightly
      kavita_canary:
        ansible_user: podman
        kavita_version: canary
verifier:
  name: ansible
